global using System.Drawing;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using AdventOfCode.Common.Extensions;
global using AdventOfCode.Common.Helpers;
global using AdventOfCode.Common.Services;
global using AdventOfCode.Common.Services.Interfaces;
global using Xunit;
global using Xunit.Abstractions;
